name: 'dbt_snp500'
version: '1.0.0'

profile: 'snp500'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_snp500:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    mart:
      +materialized: table